// Demo data for when Supabase is not configured
export const demoUserProfile = {
  id: 'demo-user',
  user_id: 'demo-user',
  email: 'demo@mindgains.ai',
  full_name: 'Arjun Sharma',
  avatar_url: null,
  bio: 'UPSC Aspirant • Delhi University • Target: IAS 2025',
  created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoUserStats = {
  id: 'demo-stats',
  user_id: 'demo-user',
  total_xp: 3250,
  current_level: 6,
  missions_completed: 18,
  streak_days: 12,
  last_activity_date: new Date().toISOString().split('T')[0],
  rank: 'Advanced Scholar',
  total_study_time: 2400, // 40 hours in minutes
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const demoMissions = [
  {
    id: 'demo-mission-1',
    user_id: 'demo-user',
    title: 'Indian Constitution - Fundamental Rights',
    description: 'Master Articles 12-35 for UPSC Prelims & Mains',
    subject_id: null,
    content_type: 'text' as const,
    content_text: 'Fundamental Rights of Indian Constitution',
    difficulty: 'medium' as const,
    status: 'active' as const,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-mission-2',
    user_id: 'demo-user',
    title: 'Mughal Empire - Complete Timeline',
    description: 'From Babur to Aurangzeb - All major rulers and events',
    subject_id: null,
    content_type: 'text' as const,
    content_text: 'Mughal Empire History',
    difficulty: 'hard' as const,
    status: 'active' as const,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-mission-3',
    user_id: 'demo-user',
    title: 'Indian Geography - Rivers & Mountains',
    description: 'Physical features crucial for competitive exams',
    subject_id: null,
    content_type: 'text' as const,
    content_text: 'Indian Physical Geography',
    difficulty: 'easy' as const,
    status: 'completed' as const,
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoSubjects = [
  {
    id: '1',
    name: 'UPSC',
    description: 'Civil Services Examination',
    icon: '🏛️',
    color: '#8b5cf6',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'JEE/NEET',
    description: 'Engineering & Medical Entrance',
    icon: '🔬',
    color: '#10b981',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Banking',
    description: 'Banking Sector Exams',
    icon: '💰',
    color: '#fbbf24',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'SSC',
    description: 'Staff Selection Commission',
    icon: '📝',
    color: '#3b82f6',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'State PCS',
    description: 'State Public Service Commission',
    icon: '🗺️',
    color: '#ec4899',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'GATE',
    description: 'Graduate Aptitude Test in Engineering',
    icon: '💻',
    color: '#06b6d4',
    created_at: new Date().toISOString(),
  },
];

export const demoAchievements = [
  {
    id: '1',
    name: 'First Steps',
    description: 'Complete your first learning mission',
    icon: '🎯',
    category: 'learning',
    required_value: 1,
    xp_reward: 50,
    badge_color: '#10b981',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Speed Demon',
    description: 'Complete a mission in under 5 minutes',
    icon: '⚡',
    category: 'speed',
    required_value: 1,
    xp_reward: 100,
    badge_color: '#fbbf24',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Perfect Score',
    description: 'Get 100% on any test',
    icon: '🏆',
    category: 'mastery',
    required_value: 1,
    xp_reward: 200,
    badge_color: '#8b5cf6',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Knowledge Seeker',
    description: 'Complete 10 missions',
    icon: '📚',
    category: 'learning',
    required_value: 10,
    xp_reward: 300,
    badge_color: '#8b5cf6',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Streak Master',
    description: 'Maintain a 7-day learning streak',
    icon: '🔥',
    category: 'streak',
    required_value: 7,
    xp_reward: 400,
    badge_color: '#ec4899',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const demoUserAchievements = [
  {
    id: 'ua1',
    user_id: 'demo-user',
    achievement_id: '1',
    progress: 1,
    completed: true,
    completed_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'ua2',
    user_id: 'demo-user',
    achievement_id: '2',
    progress: 1,
    completed: true,
    completed_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'ua3',
    user_id: 'demo-user',
    achievement_id: '3',
    progress: 1,
    completed: true,
    completed_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const demoAppStats = {
  totalUsers: 156789,
  totalMissions: 89234,
  activeUsers: 12456,
};

// Marketing data for India's #1 educational AI app
export const demoMarketingData = {
  userGrowth: [
    { month: 'Jan 2024', users: 25000 },
    { month: 'Feb 2024', users: 45000 },
    { month: 'Mar 2024', users: 78000 },
    { month: 'Apr 2024', users: 112000 },
    { month: 'May 2024', users: 156789 },
  ],
  examSuccess: {
    upsc: { attempts: 2340, success: 1876, rate: 80.2 },
    jee: { attempts: 5670, success: 4536, rate: 80.0 },
    neet: { attempts: 3450, success: 2760, rate: 80.0 },
    banking: { attempts: 8900, success: 7120, rate: 80.0 },
  },
  testimonials: [
    {
      name: 'Priya Sharma',
      exam: 'UPSC CSE 2024',
      rank: 'AIR 47',
      quote: 'MindGains AI helped me crack UPSC! The AI-generated content was exactly what I needed.',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    },
    {
      name: 'Rahul Kumar',
      exam: 'JEE Advanced 2024',
      rank: 'AIR 156',
      quote: 'The 4-room learning system is genius! Physics became so much easier.',
      avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=150',
    },
    {
      name: 'Anjali Patel',
      exam: 'SBI PO 2024',
      rank: 'Selected',
      quote: 'Banking exam prep became effortless with MindGains AI. Highly recommended!',
      avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=150',
    },
  ],
};